### ISSUE TITLE
IOS is a good fit,but android, pictures and title have a problem

### ISSUE THREAD

**Issue by dongodngtang** [Benjamin-Dobell/react-native-markdown-view#1]
IOS is a good fit,but android, pictures and title have a problem

**Comment by Benjamin-Dobell** [comment]
@dongodngtang Sorry, I just saw this.

Do you have any specifics you could offer? Screenshots etc.

I'm using this in an upcoming app of mine, but at present picture and title usage is very limited at the moment, so it's very possible I've missed something.

**Comment by gabceb** [comment]
@Benjamin-Dobell I am currently testing you library and experienced some Android issues with headers. See screenshot and Markdown code below. Note that only a part of the screen is rendered via Markdown (the only with the code below)

```
<MarkdownView>
          ### Here is my Header! 
          {'\n'}
          * List here{'\n'}
          * With some items{'\n'}
          * And this is the last time{'\n'}

          [www.tes.com/jobs](\"http://www.tes.com/jobs\")

          {'\n'}

          And some **Bold** and _Italics_ and some underline
        </MarkdownView>
```

![image](https://user-images.githubusercontent.com/470852/30279962-db216230-970e-11e7-9a89-4759f215cced.png)

**Comment by Benjamin-Dobell** [comment]
1.1.3 should address this. Please let me know if that's not the case.

**Comment by gabceb** [comment]
Works beautifully. Thanks @Benjamin-Dobell
