### ISSUE TITLE
Text and image render issue

### ISSUE THREAD

**Issue by dancomanlive** [Benjamin-Dobell/react-native-markdown-view#16]
On ios the text does not appear most of the time along with the image. Please see 
http://www.giphy.com/gifs/3o752biNNk2Kr0vBdu

Below is the code I am using for rendering the markdown. The topic that opens and closes is using Accordion from 'react-native-collapsible/Accordion';

```jsx
<Accordion
            sections={facts}
            renderHeader={(section, index, isActive) => this.renderHeader(section, index, isActive)}
            renderContent={this.renderContent}
            activeSection={this.state.activeSection}
          />
```

```jsx
renderContent(section) {
    return (
      <View style={{ backgroundColor: 'white', justifyContent: 'center', alignItems: 'center' }}>
        <MarkdownView
          onLinkPress={url => Linking.openURL(url)}
          style={{ paddingHorizontal: 10 }}
        >
          {section.value}
        </MarkdownView>
      </View>
    );
  }
```

**Comment by lukewlms** [comment]
@dancomanlive It should help if you can include a minimal repro case of the markdown you are trying to render.

**Comment by dancomanlive** [comment]
@lukewlms Hi, I would gladly do it but now I changed everything to HTML because of this issue. If you build a dummy project to recreate this issue let me know please : )

**Comment by lukewlms** [comment]
Ah too bad.  Recommend closing this issue due to no available repro case.

**Comment by Benjamin-Dobell** [comment]
Feel free to post a repro, codepen etc. and I'll reopen.
