### ISSUE TITLE
Heading rendeing issues

### ISSUE THREAD

**Issue by terrysahaidak** [Benjamin-Dobell/react-native-markdown-view#2]
I have some issue with heading rendering.

I've tried to render this text:

```
# Heading 1 \n
# Heading 2
```

It renders like 
![image](https://user-images.githubusercontent.com/7809008/27260224-7d47bcd0-542f-11e7-9d02-d7387a7bd816.png)

But should renders like 
![image](https://user-images.githubusercontent.com/7809008/27260233-b4fd7e94-542f-11e7-9070-6164e8c35b46.png)

But it requires extra newline character after heading to render like the second screenshot.

```
# Heading 1 \n
\n
# Heading 2
```

**Comment by Jhonte** [comment]
Plus one.    Was just about to ask why the extra line-break is needed.

`# MarkdownView{'\n'}
  {'\n'}`

**Comment by terrysahaidak** [comment]
Can we disable that extra-line requirement for all cases?

**Comment by Benjamin-Dobell** [comment]
Definitely agree this is a pain, however the behaviour is inherited from https://github.com/Khan/simple-markdown. Please open an issue there.

I'll happily update the dependency once the issue is fixed.

**Comment by xvonabur** [comment]
Does anybody has problem with no heading at all on Android? I've tried debug/production builds with simulator/real device, but header does not render at all.

Here is my code:

```javascript
<MarkdownView>
        ## MarkdownView{'\n'} {'\n'}
        # MarkdownView{'\n'} {'\n'}
        ### MarkdownView{'\n'} {'\n'}
        **React Native** is even better with Markdown!{'\n'}
        {'\n'}

      </MarkdownView>
```

And it renders like this:

<img width="270" alt="screen shot 2017-08-15 at 22 55 57" src="https://user-images.githubusercontent.com/616857/29333611-13de25de-820d-11e7-8948-055a13534e8b.png">

**Comment by ariabuckles** [comment]
@Benjamin-Dobell sent you PR #6 to address this!

I might address this in simple-markdown in the future, but I'm going to wait until I'm confident I'm not breaking any existing usecases and that it's the right decision for simple-markdown's high-level goals.
