### ISSUE TITLE
"text" style key overriding other styles

### ISSUE THREAD

**Issue by jamsch** [Benjamin-Dobell/react-native-markdown-view#22]
Take the following as an example: 

```javascript
const styles = {
  heading2: {
    fontSize: 20,
    marginVertical: 15,
    fontWeight: 'bold',
  },
  text: {
    color: '#000',
    fontSize: 16,
  },
}
```
The above example has `text` is overriding any of `heading2`'s rules. I still want to keep the text style as a default.

Updated: noticed that the `paragraph` rule allows for this.

```
const styles = {
  heading2: {
    color: '#000',
    fontSize: 20,
    marginVertical: 15,
    fontWeight: 'bold',
  },
  paragraph: {
    color: '#000',
    fontSize: 16,
  },
}
`

**Comment by martsie** [comment]
Thanks for this issue, helped me figure out why headings weren't resizing properly for me.
