### ISSUE TITLE
Typescript type definition

### ISSUE THREAD

**Issue by rodrigoelp** [Benjamin-Dobell/react-native-markdown-view#26]
Browsing the repo I can see there is no typescript type definition, do you guys have the API documentation that I can use to generate the definition?

**Comment by rodrigoelp** [comment]
Hi @Benjamin-Dobell, You will find the pull request #29 in which I have added the type definition.

I've test it but it does not cover the entire API as I couldn't find an example of how to consume it with rules (for instance)

**Comment by rodrigoelp** [comment]
About a year since I contributed here. No answer though

**Comment by lyqht** [comment]
@Benjamin-Dobell Bump!

**Comment by Benjamin-Dobell** [comment]
Closed by #29.
