### ISSUE TITLE
Content partially not showing

### ISSUE THREAD

**Issue by dancomanlive** [Benjamin-Dobell/react-native-markdown-view#3]
![screen shot 2017-07-17 at 12 19 28 pm](https://user-images.githubusercontent.com/16872821/28255584-6c420fb2-6aeb-11e7-9ced-b6e188430ed8.png)

**Comment by dancomanlive** [comment]
This only happens once every few tries btw.

`<MarkdownView
          onLinkPress={url => Linking.openURL(url)}
          style={{ paddingHorizontal: 10 }}
          styles={{
            image: {
              marginLeft: -10,
              resizeMode: 'contain',
            },
            imageWrapper: {
              width,
              padding: 0
            },
            paragraph: {
              marginTop: 10,
              marginBottom: 10,
            }
          }}
          // style={{ paddingHorizontal: 10 }}
        >
          {section.value}
        </MarkdownView>`

**Comment by Benjamin-Dobell** [comment]
Could you please include an example of the Markdown text (`section.value`) that should be rendered?

Also, given you've described this as intermittent, a screenshot of rendering working vs. not working would be ideal.

It's hard to tell with limited information, but I would expect this sort of behaviour to be the result of an application bug (async race condition etc.), although I could be wrong. Where is `section.value` coming from?

**Comment by dancomanlive** [comment]
Thanks for the quick reply. The issue was due to fixed width and height of images. This was just fixed(see link to fork) to take the original width and height of the images   https://github.com/LizardApps/react-native-markdown-view/commit/cc91c927fc09657fca9982bd015c1d97ce2a519c

**Comment by Benjamin-Dobell** [comment]
I'm closing this now as I think the issue may have specifically been with your styles/customisation. However, if that's not the case please comment here with an explanation and I'll re-open.
